"""
review_pool.py — 真实风格评论池（手写，基于各云厂商真实产品体验推断）

每条评论包含: competitor_id, platform, author, rating, content, sentiment_score
"""
import random
from datetime import datetime, timedelta


# 所有评论都模拟真实用户在真实平台的发言风格
# 覆盖正面/负面/中性三种情感，涉及具体产品、具体场景

REVIEW_POOL = [
    # ═══════════════════════════════════════════════════════════
    # 阿里云 (competitor_id=1) — 20 条
    # ═══════════════════════════════════════════════════════════
    dict(cid=1, platform="知乎", author="架构师老张", rating=4.0,
        content="ECS 稳定性不错，双11期间也没出问题。但RDS的自动备份偶尔延迟，提过工单后改善不少。整体生态完善，文档质量比腾讯云好一档。",
        sentiment=0.55),
    dict(cid=1, platform="小红书", author="DevOps小李", rating=3.5,
        content="ACK Pro 上手比想象中复杂，YAML配置项太多了。跑通后确实省心，但学习成本偏高。希望能出个新手引导模式。",
        sentiment=-0.15),
    dict(cid=1, platform="开发者社区", author="码农小刘", rating=4.5,
        content="通义千问 API 接入很方便，Python SDK 三行代码搞定。长文本理解能力比半年前提升明显，价格也很友好。",
        sentiment=0.72),
    dict(cid=1, platform="知乎", author="技术VP王总", rating=4.0,
        content="OSS+CDN+ECS全在阿里云，三年了没换过。贵是贵了点但省心。被AWS的复杂计费吓退过一次后再没想过换。",
        sentiment=0.35),
    dict(cid=1, platform="CSDN", author="后端工程师阿明", rating=3.0,
        content="Redis集群版扩容时发生过一次数据倾斜，工单响应倒是快但排查了一天。文档里对集群模式的特有限制说明太少。",
        sentiment=-0.40),
    dict(cid=1, platform="掘金", author="云原生玩家", rating=4.5,
        content="ACK 的多集群管理做得不错，跨地域流量调度很方便。相比自建 K8s 运维成本降了至少 60%。",
        sentiment=0.68),
    dict(cid=1, platform="知乎", author="SRE小陈", rating=3.5,
        content="监控告警阈值设置不够灵活，自定义指标要额外买PLUS版。Prometheus+grafana自建反而更自由。",
        sentiment=-0.10),
    dict(cid=1, platform="InfoQ", author="CTO周", rating=4.0,
        content="通义千问在代码生成场景表现超出预期，Copilot平替效果不错。期待 Qwen2.5 的推理速度提升。",
        sentiment=0.50),
    dict(cid=1, platform="V2EX", author="全栈阿杰", rating=3.5,
        content="OSS的图片处理功能挺方便，但批量操作的API限流有点狠，超过1000个文件就得排队。",
        sentiment=0.05),
    dict(cid=1, platform="知乎", author="数据工程师小林", rating=4.5,
        content="MaxCompute跑TB级数据比自建Hadoop快3倍以上。就是SQL方言和其他平台差异大，迁移有学习成本。",
        sentiment=0.60),
    dict(cid=1, platform="开发者社区", author="Java后端老周", rating=2.5,
        content="RDS MySQL 8.0升级到8.0.36后，部分连表查询性能下降了30%，回滚了才正常。希望阿里云在升级前多做兼容性测试。",
        sentiment=-0.55),
    dict(cid=1, platform="小红书", author="创业小张", rating=4.0,
        content="用阿里云三年了，从ECS到函数计算全栈都在这。唯一不爽的是ACP认证考试费涨了。",
        sentiment=0.30),
    dict(cid=1, platform="OSCHINA", author="运维老杨", rating=3.0,
        content="DDoS高防IP的价格是腾讯云1.5倍，效果确实好但小公司扛不住。希望出轻量版方案。",
        sentiment=-0.25),
    dict(cid=1, platform="知乎", author="安全工程师阿凯", rating=4.5,
        content="阿里云安全中心(WAF+DDoS+堡垒机)在等保测评时省了至少一个月整改时间。合规方面确实国内第一。",
        sentiment=0.70),
    dict(cid=1, platform="掘金", author="前端小赵", rating=4.0,
        content="CDN加速效果很明显，静态资源全国平均加载时间从1.2s降到0.3s。配置缓存规则也很直观。",
        sentiment=0.55),
    dict(cid=1, platform="CSDN", author="测试工程师刘", rating=2.0,
        content="PTS压测工具居然不支持WebSocket协议，只能用JMeter替代。都2025年了这点还没跟上。",
        sentiment=-0.65),
    dict(cid=1, platform="知乎", author="AI产品经理", rating=4.5,
        content="百炼平台的模型管理比百度AI云好用，模型版本对比和A/B测试功能很完善。但模型市场里第三方模型太少。",
        sentiment=0.48),
    dict(cid=1, platform="V2EX", author="独立开发者", rating=3.5,
        content="函数计算冷启动有时要2秒，对用户感知还是挺明显的。预留实例又太贵。",
        sentiment=-0.12),
    dict(cid=1, platform="InfoQ", author="架构师孙", rating=4.0,
        content="阿里云的混合云方案(ACK One)在多家子公司统一管理场景下表现不错。但多集群成本分摊报表做得很粗糙。",
        sentiment=0.25),
    dict(cid=1, platform="小红书", author="数据分析师小吴", rating=3.0,
        content="DataWorks的调度逻辑偶尔会出现依赖检查失败，明明上游成功了就是卡住不跑下游。手动重跑又正常了，很玄学。",
        sentiment=-0.35),

    # ═══════════════════════════════════════════════════════════
    # 腾讯云 (competitor_id=2) — 20 条
    # ═══════════════════════════════════════════════════════════
    dict(cid=2, platform="知乎", author="游戏架构师", rating=4.5,
        content="腾讯云在游戏场景比其他家强太多，GME+TRTC延迟很低，东南亚优化也很好。唯一槽点是国际站文档中英文混排。",
        sentiment=0.62),
    dict(cid=2, platform="V2EX", author="前端小王", rating=3.5,
        content="COS 的 Web 控制台上传大文件经常卡住，API上传倒是正常。CDN预热偶尔要等5分钟以上。",
        sentiment=-0.20),
    dict(cid=2, platform="开发者社区", author="全栈老赵", rating=4.0,
        content="TDSQL 在分库分表场景比开源 MySQL 好管太多，自动负载均衡很省心。金融客户POC时性能压测轻松过。",
        sentiment=0.48),
    dict(cid=2, platform="知乎", author="视频技术专家", rating=4.5,
        content="腾讯云音视频 SDK 确实业界最强，弱网优化明显。直播延迟控制在1秒内，比华为云方案好。",
        sentiment=0.75),
    dict(cid=2, platform="小红书", author="创业CTO", rating=3.0,
        content="小程序云开发限制有点多，复杂业务逻辑还是得自己搭Node服务。不过对MVP阶段确实够用。",
        sentiment=-0.25),
    dict(cid=2, platform="OSCHINA", author="运维阿杰", rating=4.0,
        content="CVM的竞价实例比阿里云便宜15%左右，离线计算任务用起来性价比很高。但抢占概率也高一些。",
        sentiment=0.40),
    dict(cid=2, platform="知乎", author="数据工程师", rating=3.5,
        content="WeData数据开发平台功能全但UI太复杂了，新人上手至少两周。比起DataWorks少了些模板。",
        sentiment=-0.05),
    dict(cid=2, platform="掘金", author="后端老何", rating=4.5,
        content="TDSQL的Oracle兼容模式帮我们省了至少半年的迁移时间，存储过程和触发器基本无缝跑通。",
        sentiment=0.78),
    dict(cid=2, platform="CSDN", author="安卓开发小赵", rating=2.5,
        content="腾讯云IM SDK的文档更新太慢了，新版API已经上线两个月了文档还是旧的。照着文档写一堆过时代码。",
        sentiment=-0.50),
    dict(cid=2, platform="知乎", author="SRE团队Lead", rating=4.0,
        content="腾讯云CLS日志服务的查询语法比阿里云SLS灵活，支持SQL分析。但日志保留7天以上价格翻倍。",
        sentiment=0.32),
    dict(cid=2, platform="V2EX", author="游戏后端小刘", rating=3.0,
        content="CVM的GPU实例经常缺货，A100要提前一周预约。做AI训练的真等不起。",
        sentiment=-0.38),
    dict(cid=2, platform="InfoQ", author="技术总监", rating=4.0,
        content="腾讯会议的API集成到企业OA后，内部会议效率提升明显。但录制文件的转码时间有点长。",
        sentiment=0.45),
    dict(cid=2, platform="小红书", author="前端新手", rating=2.0,
        content="云开发的数据库权限控制太粗了，只能按集合粒度设置，不能按字段。安全性不够。",
        sentiment=-0.60),
    dict(cid=2, platform="知乎", author="金融科技工程师", rating=4.5,
        content="TDSQL在核心交易系统的TPC-C跑分比开源MySQL高40%，确实有两把刷子。不过DBA学习曲线陡峭。",
        sentiment=0.65),
    dict(cid=2, platform="开发者社区", author="DevOps小梅", rating=3.5,
        content="容器服务TKE的节点自动扩缩容策略不如ACK灵活，只能设CPU/内存阈值，不能自定义指标。",
        sentiment=-0.08),
    dict(cid=2, platform="CSDN", author="音视频开发老郑", rating=5.0,
        content="TRTC的AI降噪v3.0效果惊艳，咖啡馆背景音消得干干净净。比阿里云的RTC方案强至少一个档次。",
        sentiment=0.88),
    dict(cid=2, platform="知乎", author="出海创业者", rating=3.5,
        content="腾讯云新加坡节点比阿里云便宜20%左右，东南亚用户延迟也低。但工单只能用英文，中文支持要排很久。",
        sentiment=0.10),
    dict(cid=2, platform="OSCHINA", author="DBA老王", rating=2.5,
        content="云数据库MySQL的binlog清理策略太激进，想回滚到24小时前的状态发现日志已经被清了。",
        sentiment=-0.45),
    dict(cid=2, platform="掘金", author="全栈工程师", rating=4.0,
        content="CloudBase(云开发)的CLI工具比阿里云的好用，本地调试和部署一键完成。小程序开发效率很高。",
        sentiment=0.50),
    dict(cid=2, platform="知乎", author="安全研究员", rating=3.0,
        content="腾讯云WAF的规则更新频率不如阿里云，新出的漏洞有时候要等一两天才有防护规则。",
        sentiment=-0.30),

    # ═══════════════════════════════════════════════════════════
    # 华为云 (competitor_id=3) — 20 条
    # ═══════════════════════════════════════════════════════════
    dict(cid=3, platform="知乎", author="金融IT总监", rating=4.5,
        content="GaussDB替代Oracle进展超出预期。核心交易系统迁移后性能不降反升，华为原厂支持也很到位。",
        sentiment=0.78),
    dict(cid=3, platform="CSDN", author="AI研究员", rating=5.0,
        content="ModelArts的分布式训练效率极高，千卡集群的线性加速比达到0.92。昇腾910B的推理延迟比A100低15%。",
        sentiment=0.85),
    dict(cid=3, platform="知乎", author="政务信息化", rating=4.0,
        content="华为云在政务网合规方面无可替代。等保三级+密评一站式过，其他厂商至少多花两个月。",
        sentiment=0.55),
    dict(cid=3, platform="掘金", author="后端小郑", rating=3.5,
        content="ECS 和 OBS 中规中矩，但API设计风格不如阿里云统一。不同产品线的SDK命名规范不一致。",
        sentiment=-0.18),
    dict(cid=3, platform="开发者社区", author="ML工程师", rating=4.5,
        content="盘古大模型在B端场景的指令遵循能力很强。测试了合同审核、招标分析、客服总结三个场景，准确率都在85%以上。",
        sentiment=0.70),
    dict(cid=3, platform="InfoQ", author="架构师刘", rating=4.0,
        content="华为云的容灾方案考虑很周全，两地三中心+同城双活配置文档清晰。POC时故障切换RPO=0，RTO<30秒。",
        sentiment=0.52),
    dict(cid=3, platform="知乎", author="电信工程师", rating=4.0,
        content="华为云在运营商行业的积累很深，NFV/SDN方案比其他云成熟。但面向互联网行业的产品灵活度不够。",
        sentiment=0.38),
    dict(cid=3, platform="V2EX", author="SRE工程师", rating=3.0,
        content="OBS的跨区域复制延迟比阿里云OSS高不少，华北到华南经常差3秒以上。对数据一致性要求高的场景不太够。",
        sentiment=-0.33),
    dict(cid=3, platform="CSDN", author="大数据工程师", rating=4.0,
        content="MRS(Hadoop/Spark)的存算分离架构比开源方案节省了40%存储成本。但组件升级时依赖关系太复杂。",
        sentiment=0.42),
    dict(cid=3, platform="小红书", author="AI创业者", rating=3.5,
        content="昇腾910B的算力确实强，但MindSpore框架的社区资源比PyTorch少太多了，模型移植很花时间。",
        sentiment=-0.20),
    dict(cid=3, platform="知乎", author="央企IT负责人", rating=4.5,
        content="华为云Stack的本地部署+云上AI推理混合方案是目前信创环境下的最优解。安全和性能平衡得很好。",
        sentiment=0.72),
    dict(cid=3, platform="开发者社区", author="数据库DBA", rating=4.0,
        content="GaussDB的并行查询引擎很厉害，32核并行扫描10亿行数据不到3秒。但执行计划分析工具还需改进。",
        sentiment=0.55),
    dict(cid=3, platform="OSCHINA", author="运维小袁", rating=2.5,
        content="华为云的RAM权限管理太复杂了，策略语法和AWS IAM类似但文档不够详细，新手很容易配错。",
        sentiment=-0.40),
    dict(cid=3, platform="知乎", author="自动驾驶公司CTO", rating=4.5,
        content="华为云+华为MDC的组合在自动驾驶数据闭环中效率最高。数据从车端上传到云端训练全链路优化得很好。",
        sentiment=0.68),
    dict(cid=3, platform="掘金", author="前端小黄", rating=3.0,
        content="华为云的控制台界面设计太'硬核'了，信息密度大但视觉层次不清晰。新用户找功能要花很长时间。",
        sentiment=-0.28),
    dict(cid=3, platform="InfoQ", author="技术VP马", rating=4.0,
        content="华为云的产业云方案在制造业落地效果很好，工业数据中台+AI质检直接跑通了产线。互联网公司可能无感。",
        sentiment=0.48),
    dict(cid=3, platform="CSDN", author="学生开发者", rating=2.0,
        content="华为云对个人开发者的扶持不够，学生优惠只有6个月，到期后续费原价承受不了。阿里云学生计划好很多。",
        sentiment=-0.58),
    dict(cid=3, platform="知乎", author="安全合规专家", rating=4.5,
        content="华为云的加密方案(HSM+KMS)通过了国密局认证，金融客户审计时零问题项。其他云在这块差距明显。",
        sentiment=0.75),
    dict(cid=3, platform="V2EX", author="后端小彭", rating=3.0,
        content="CSE微服务引擎的配置中心偶尔出现配置推送延迟，导致多实例间配置不一致。排查起来很头痛。",
        sentiment=-0.35),
    dict(cid=3, platform="小红书", author="产品经理", rating=3.5,
        content="华为云的产品命名太工程化了(ModelArts/GaussDB/DataArts)，给老板汇报时每次都要解释一遍。",
        sentiment=-0.05),

    # ═══════════════════════════════════════════════════════════
    # AWS 中国 (competitor_id=4) — 15 条
    # ═══════════════════════════════════════════════════════════
    dict(cid=4, platform="知乎", author="外企CTO", rating=4.5,
        content="全球部署绕不开AWS。中国区虽然产品少一些但核心服务稳定。跨国企业的合规方案只有AWS最成熟。",
        sentiment=0.65),
    dict(cid=4, platform="V2EX", author="海归工程师", rating=3.0,
        content="中国区S3的权限模型和Global版行为不同，跨国团队踩过不少坑。希望尽快和Global版保持一致。",
        sentiment=-0.30),
    dict(cid=4, platform="知乎", author="安全专家", rating=4.5,
        content="AWS IAM的权限粒度控制是所有云里最强的。Security Hub+GuardDuty的组合在等保审计时省了很多力气。",
        sentiment=0.72),
    dict(cid=4, platform="CSDN", author="DevOps小吴", rating=3.5,
        content="EC2和RDS比国内厂商贵30%以上，但SLA确实靠谱。三年没遇到过无通知的可用区故障。",
        sentiment=0.05),
    dict(cid=4, platform="知乎", author="创业公司CTO", rating=3.0,
        content="账单太复杂了，RI/SavingsPlan/Spot 三种计费模式算不清楚。小团队根本用不起，我们还是切回了阿里云。",
        sentiment=-0.45),
    dict(cid=4, platform="开发者社区", author="架构师张", rating=4.0,
        content="Lambda+API Gateway做Serverless很舒服。就是冷启动延迟对中文用户来说偏高（宁夏节点）。",
        sentiment=0.30),
    dict(cid=4, platform="InfoQ", author="首席架构师", rating=4.0,
        content="AWS的EKS比国内厂商的自建K8s稳定太多，升级控制面零中断。但中国区EKS的版本更新比Global慢3个月。",
        sentiment=0.35),
    dict(cid=4, platform="知乎", author="出海SaaS创始人", rating=4.5,
        content="AWS是全球SaaS的唯一选择。新加坡+法兰克福+弗吉尼亚三个区域部署后，全球用户延迟都在50ms以内。",
        sentiment=0.80),
    dict(cid=4, platform="V2EX", author="开发者小许", rating=2.5,
        content="AWS中国区的支持团队响应不如Global版，P1级别的工单等了4小时才有人跟进。价格还比国际版贵。",
        sentiment=-0.50),
    dict(cid=4, platform="CSDN", author="大数据架构师", rating=4.0,
        content="EMR+Athena+Glue的数据湖方案很成熟。就是中国区Athena查询S3的数据要跨region，额外收流量费。",
        sentiment=0.28),
    dict(cid=4, platform="知乎", author="传统企业IT经理", rating=2.0,
        content="AWS的学习曲线太陡了，200多个服务名词都搞不清楚。国内云厂商的产品体系对企业IT人员友好太多。",
        sentiment=-0.55),
    dict(cid=4, platform="掘金", author="云原生开发者", rating=4.5,
        content="AWS CDK用代码定义基础设施体验极好，TypeScript+Python都支持。对比阿里云ROS的JSON模板不是一个维度。",
        sentiment=0.70),
    dict(cid=4, platform="小红书", author="后台工程师", rating=3.0,
        content="DynamoDB的按量付费看起来便宜，但一旦流量上来费用涨得飞快。小项目可以用，大了必须精打细算。",
        sentiment=-0.18),
    dict(cid=4, platform="知乎", author="跨国零售CTO", rating=4.5,
        content="AWS的全球化一致性体验无人能敌。同样一套Terraform代码能在全球12个Region直接部署，不用改。",
        sentiment=0.75),
    dict(cid=4, platform="OSCHINA", author="运维小谢", rating=3.0,
        content="CloudWatch的告警规则配置太复杂了，比起阿里云的云监控差了一个易用性等级。每次配告警都要查文档。",
        sentiment=-0.22),

    # ═══════════════════════════════════════════════════════════
    # 百度 AI 云 (competitor_id=5) — 15 条
    # ═══════════════════════════════════════════════════════════
    dict(cid=5, platform="知乎", author="AI创业者", rating=4.5,
        content="文心一言4.0的API价格是竞品的一半，效果在中文场景不输GPT-4。对初创公司太友好了。",
        sentiment=0.75),
    dict(cid=5, platform="CSDN", author="NLP工程师", rating=4.0,
        content="ERNIE SDK文档详尽，Fine-tune流程很顺。但模型版本管理还比较原始，不如HuggingFace生态成熟。",
        sentiment=0.42),
    dict(cid=5, platform="V2EX", author="独立开发者", rating=3.5,
        content="BCC 性价比确实高，但控制台响应有点慢，切换Tab经常转圈。希望能优化前端性能。",
        sentiment=-0.22),
    dict(cid=5, platform="知乎", author="智能客服产品经理", rating=4.0,
        content="百度OCR的识别准确率比阿里云高5个点。增值税发票和营业执照识别基本零错误。",
        sentiment=0.55),
    dict(cid=5, platform="开发者社区", author="全栈小黄", rating=3.0,
        content="云函数BaaS的冷启动时间比AWS Lambda长不少。文档虽全但例子太少。",
        sentiment=-0.35),
    dict(cid=5, platform="知乎", author="自动驾驶工程师", rating=4.5,
        content="Apollo平台的数据标注工具效率很高。对比自建方案省了40%的标注人力。高精地图更新频率也够用。",
        sentiment=0.68),
    dict(cid=5, platform="InfoQ", author="技术Lead", rating=4.0,
        content="百度云的AI产品矩阵是最全的，从NLP到CV到语音到知识图谱一应俱全。但非AI的基础云服务还需加强。",
        sentiment=0.40),
    dict(cid=5, platform="小红书", author="电商运营", rating=3.5,
        content="百度智能客服的意图识别准确率比去年提升明显，但对话流程设计工具还是太僵硬，不够灵活。",
        sentiment=0.08),
    dict(cid=5, platform="掘金", author="后端小何", rating=2.5,
        content="BCC的可用区故障发生过两次，虽然都恢复了但通知不及时。希望加强可用区级别的冗余保障。",
        sentiment=-0.48),
    dict(cid=5, platform="知乎", author="医疗AI公司CTO", rating=4.0,
        content="百度在医疗NLP领域的积累很深，病历结构化、ICD编码推荐准确率都在90%以上。合规做得也不错。",
        sentiment=0.60),
    dict(cid=5, platform="CSDN", author="学生开发者", rating="4.0",
        content="百度云对学生的免费额度很大方，文心一言API一个月给100万token免费额度，做课程项目完全够用。",
        sentiment=0.52),
    dict(cid=5, platform="V2EX", author="SRE工程师", rating=2.0,
        content="BOS的跨区域复制居然不支持增量同步，每次都是全量。100TB数据复制一次要跑好几天。",
        sentiment=-0.62),
    dict(cid=5, platform="知乎", author="金融AI负责人", rating=4.0,
        content="文心大模型在金融领域的微调效果不错，风险识别和反欺诈场景准确率超过了通用模型。",
        sentiment=0.58),
    dict(cid=5, platform="开发者社区", author="前端小刘", rating=3.0,
        content="百度云的移动端SDK集成体验不太好，Android和iOS的API不一致，文档也没有统一说明。",
        sentiment=-0.28),
    dict(cid=5, platform="知乎", author="制造业数字化转型", rating=3.5,
        content="百度工业AI的质检方案在产线上跑了半年，误报率从5%降到了1.2%。但硬件兼容性还有提升空间。",
        sentiment=0.32),
]


def get_random_review():
    """从评论池中随机选择一条，并加上随机的时间偏移"""
    review = random.choice(REVIEW_POOL)
    # 随机偏移 0-10 天
    days_offset = random.randint(0, 10)
    hours_offset = random.randint(0, 23)
    timestamp = datetime.utcnow() - timedelta(days=days_offset, hours=hours_offset)
    return {
        "competitor_id": review["cid"],
        "platform": review["platform"],
        "author": review["author"],
        "rating": review["rating"],
        "content": review["content"],
        "sentiment_score": review["sentiment"],
        "review_date": timestamp,
        "collected_at": timestamp,
    }


def get_reviews_for_competitor(cid: int, count: int = 3):
    """获取指定竞品的 N 条随机评论"""
    pool = [r for r in REVIEW_POOL if r["cid"] == cid]
    selected = random.sample(pool, min(count, len(pool)))
    result = []
    for r in selected:
        days_offset = random.randint(0, 10)
        hours_offset = random.randint(0, 23)
        timestamp = datetime.utcnow() - timedelta(days=days_offset, hours=hours_offset)
        result.append({
            "competitor_id": r["cid"],
            "platform": r["platform"],
            "author": r["author"],
            "rating": r["rating"],
            "content": r["content"],
            "sentiment_score": r["sentiment"],
            "review_date": timestamp,
            "collected_at": timestamp,
        })
    return result
