"""Initial tables

Revision ID: 5d2a769d48aa
Revises: 
Create Date: 2026-04-22 15:47:41.797963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2a769d48aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('insight', sa.Text(), nullable=False))
    op.add_column('analysis_reports', sa.Column('evidence_json', sa.Text(), nullable=False))
    op.add_column('analysis_reports', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('analysis_reports', sa.Column('recommendations_json', sa.Text(), nullable=False))
    op.add_column('analysis_reports', sa.Column('model_name', sa.String(length=64), nullable=False))
    op.add_column('analysis_reports', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.alter_column('analysis_reports', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('analysis_reports', 'report_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False,
               existing_server_default=sa.text("'insight'"))
    op.drop_index('idx_reports_comp', table_name='analysis_reports')
    op.create_index(op.f('ix_analysis_reports_competitor_id'), 'analysis_reports', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_timestamp'), 'analysis_reports', ['timestamp'], unique=False)
    op.drop_column('analysis_reports', 'created_at')
    op.drop_column('analysis_reports', 'report_data')
    op.alter_column('competitors', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('competitors', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('competitors', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('competitors', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now','localtime'))"))
    op.alter_column('competitors', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now','localtime'))"))
    op.create_index(op.f('ix_competitors_name'), 'competitors', ['name'], unique=True)
    op.drop_column('competitors', 'status')
    op.drop_column('competitors', 'price_index')
    op.drop_column('competitors', 'user_rating')
    op.drop_column('competitors', 'frequency')
    op.drop_column('competitors', 'type')
    op.drop_column('competitors', 'market_share')
    op.drop_column('competitors', 'growth')
    op.add_column('monitoring_logs', sa.Column('source_name', sa.String(length=64), nullable=False))
    op.add_column('monitoring_logs', sa.Column('source_chain', sa.Text(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('monitoring_logs', sa.Column('events_count', sa.Integer(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('metrics_json', sa.Text(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('error_message', sa.Text(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('duration_ms', sa.Integer(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.alter_column('monitoring_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('idx_logs_comp', table_name='monitoring_logs')
    op.drop_index('idx_logs_time', table_name='monitoring_logs')
    op.create_index(op.f('ix_monitoring_logs_competitor_id'), 'monitoring_logs', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_monitoring_logs_timestamp'), 'monitoring_logs', ['timestamp'], unique=False)
    op.drop_column('monitoring_logs', 'created_at')
    op.drop_column('monitoring_logs', 'event_type')
    op.drop_column('monitoring_logs', 'severity')
    op.drop_column('monitoring_logs', 'source')
    op.drop_column('monitoring_logs', 'event_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_logs', sa.Column('event_data', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
    op.add_column('monitoring_logs', sa.Column('source', sa.TEXT(), server_default=sa.text("'web_crawler'"), nullable=True))
    op.add_column('monitoring_logs', sa.Column('severity', sa.TEXT(), server_default=sa.text("'info'"), nullable=True))
    op.add_column('monitoring_logs', sa.Column('event_type', sa.TEXT(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now','localtime'))"), nullable=True))
    op.drop_index(op.f('ix_monitoring_logs_timestamp'), table_name='monitoring_logs')
    op.drop_index(op.f('ix_monitoring_logs_competitor_id'), table_name='monitoring_logs')
    op.create_index('idx_logs_time', 'monitoring_logs', ['created_at'], unique=False)
    op.create_index('idx_logs_comp', 'monitoring_logs', ['competitor_id'], unique=False)
    op.alter_column('monitoring_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('monitoring_logs', 'timestamp')
    op.drop_column('monitoring_logs', 'duration_ms')
    op.drop_column('monitoring_logs', 'error_message')
    op.drop_column('monitoring_logs', 'metrics_json')
    op.drop_column('monitoring_logs', 'events_count')
    op.drop_column('monitoring_logs', 'status')
    op.drop_column('monitoring_logs', 'source_chain')
    op.drop_column('monitoring_logs', 'source_name')
    op.add_column('competitors', sa.Column('growth', sa.REAL(), server_default=sa.text('0'), nullable=True))
    op.add_column('competitors', sa.Column('market_share', sa.REAL(), server_default=sa.text('0'), nullable=True))
    op.add_column('competitors', sa.Column('type', sa.TEXT(), server_default=sa.text("'all'"), nullable=True))
    op.add_column('competitors', sa.Column('frequency', sa.TEXT(), server_default=sa.text("'15'"), nullable=True))
    op.add_column('competitors', sa.Column('user_rating', sa.REAL(), server_default=sa.text('(4.0)'), nullable=True))
    op.add_column('competitors', sa.Column('price_index', sa.REAL(), server_default=sa.text('(90)'), nullable=True))
    op.add_column('competitors', sa.Column('status', sa.TEXT(), server_default=sa.text("'monitoring'"), nullable=True))
    op.drop_index(op.f('ix_competitors_name'), table_name='competitors')
    op.alter_column('competitors', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now','localtime'))"))
    op.alter_column('competitors', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now','localtime'))"))
    op.alter_column('competitors', 'url',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('competitors', 'name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('competitors', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('analysis_reports', sa.Column('report_data', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('analysis_reports', sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now','localtime'))"), nullable=True))
    op.drop_index(op.f('ix_analysis_reports_timestamp'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_competitor_id'), table_name='analysis_reports')
    op.create_index('idx_reports_comp', 'analysis_reports', ['competitor_id'], unique=False)
    op.alter_column('analysis_reports', 'report_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'insight'"))
    op.alter_column('analysis_reports', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('analysis_reports', 'timestamp')
    op.drop_column('analysis_reports', 'model_name')
    op.drop_column('analysis_reports', 'recommendations_json')
    op.drop_column('analysis_reports', 'confidence')
    op.drop_column('analysis_reports', 'evidence_json')
    op.drop_column('analysis_reports', 'insight')
    # ### end Alembic commands ###
