"""unified_schema_add_missing_tables

Revision ID: ec93b190edb8
Revises: 5d2a769d48aa
Create Date: 2026-04-30 13:19:38.316578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec93b190edb8'
down_revision: Union[str, None] = '5d2a769d48aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('scraper_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notification_method', sa.String(length=50), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_rules_competitor_id', 'alert_rules', ['competitor_id'], unique=False)
    op.create_table('monitoring_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monitoring_snapshots_competitor_id', 'monitoring_snapshots', ['competitor_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_competitor_id', 'price_history', ['competitor_id'], unique=False)
    op.create_table('user_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_reviews_competitor_id', 'user_reviews', ['competitor_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_history_triggered_at', 'alert_history', ['triggered_at'], unique=False)
    op.add_column('analysis_reports', sa.Column('title', sa.String(length=300), nullable=True))
    op.add_column('analysis_reports', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('analysis_reports', sa.Column('content', sa.JSON(), nullable=True))
    op.add_column('analysis_reports', sa.Column('recommendations', sa.JSON(), nullable=True))
    op.add_column('analysis_reports', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('analysis_reports', sa.Column('model_used', sa.String(length=100), nullable=True))
    op.add_column('analysis_reports', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('analysis_reports', 'report_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_analysis_reports_timestamp', table_name='analysis_reports')
    op.drop_column('analysis_reports', 'model_name')
    op.drop_column('analysis_reports', 'timestamp')
    op.drop_column('analysis_reports', 'insight')
    op.drop_column('analysis_reports', 'recommendations_json')
    op.drop_column('analysis_reports', 'evidence_json')
    op.drop_column('analysis_reports', 'confidence')
    op.add_column('changes', sa.Column('field_name', sa.String(length=100), nullable=False))
    op.add_column('changes', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('changes', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('changes', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('changes', sa.Column('detected_at', sa.DateTime(), nullable=True))
    op.add_column('changes', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('changes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('changes', 'change_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_index('idx_changes_competitor', table_name='changes')
    op.create_index('ix_changes_competitor_id', 'changes', ['competitor_id'], unique=False)
    op.create_index('ix_changes_detected_at', 'changes', ['detected_at'], unique=False)
    op.drop_constraint(None, 'changes', type_='foreignkey')
    op.create_foreign_key(None, 'changes', 'competitors', ['competitor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('changes', 'content_after')
    op.drop_column('changes', 'content_before')
    op.drop_column('changes', 'similarity')
    op.drop_column('changes', 'metadata')
    op.drop_column('changes', 'created_at')
    op.add_column('competitors', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('competitors', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('competitors', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('competitors', sa.Column('last_checked', sa.DateTime(), nullable=True))
    op.alter_column('competitors', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('competitors', 'url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('competitors', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'monitoring'"))
    op.alter_column('competitors', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('competitors', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('ix_competitors_name', table_name='competitors')
    op.create_index('ix_competitors_name', 'competitors', ['name'], unique=False)
    op.create_index('ix_competitors_category', 'competitors', ['category'], unique=False)
    op.create_index('ix_competitors_status', 'competitors', ['status'], unique=False)
    op.create_unique_constraint(None, 'competitors', ['name'])
    op.drop_column('competitors', 'feature_count')
    op.drop_column('competitors', 'innovation_velocity')
    op.drop_column('competitors', 'security_mentions')
    op.drop_column('competitors', 'market_share')
    op.drop_column('competitors', 'growth')
    op.drop_column('competitors', 'type')
    op.drop_column('competitors', 'price_index')
    op.drop_column('competitors', 'user_rating')
    op.drop_column('competitors', 'frequency')
    op.add_column('monitoring_logs', sa.Column('response_time', sa.Float(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('url', sa.String(length=500), nullable=True))
    op.add_column('monitoring_logs', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('monitoring_logs', sa.Column('content_length', sa.Integer(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('monitoring_type', sa.String(length=50), nullable=True))
    op.add_column('monitoring_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('checked_at', sa.DateTime(), nullable=True))
    op.alter_column('monitoring_logs', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('monitoring_logs', 'error_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('idx_logs_comp', table_name='monitoring_logs')
    op.drop_index('ix_monitoring_logs_timestamp', table_name='monitoring_logs')
    op.create_index('ix_monitoring_logs_checked_at', 'monitoring_logs', ['checked_at'], unique=False)
    op.drop_column('monitoring_logs', 'source_chain')
    op.drop_column('monitoring_logs', 'timestamp')
    op.drop_column('monitoring_logs', 'duration_ms')
    op.drop_column('monitoring_logs', 'source_name')
    op.drop_column('monitoring_logs', 'metrics_json')
    op.drop_column('monitoring_logs', 'events_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_logs', sa.Column('events_count', sa.INTEGER(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('metrics_json', sa.TEXT(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('source_name', sa.VARCHAR(length=64), nullable=False))
    op.add_column('monitoring_logs', sa.Column('duration_ms', sa.INTEGER(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.add_column('monitoring_logs', sa.Column('source_chain', sa.TEXT(), nullable=False))
    op.drop_index('ix_monitoring_logs_checked_at', table_name='monitoring_logs')
    op.create_index('ix_monitoring_logs_timestamp', 'monitoring_logs', ['timestamp'], unique=False)
    op.create_index('idx_logs_comp', 'monitoring_logs', ['competitor_id'], unique=False)
    op.alter_column('monitoring_logs', 'error_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('monitoring_logs', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('monitoring_logs', 'checked_at')
    op.drop_column('monitoring_logs', 'details')
    op.drop_column('monitoring_logs', 'monitoring_type')
    op.drop_column('monitoring_logs', 'content_length')
    op.drop_column('monitoring_logs', 'content_hash')
    op.drop_column('monitoring_logs', 'url')
    op.drop_column('monitoring_logs', 'response_time')
    op.add_column('competitors', sa.Column('frequency', sa.VARCHAR(length=16), server_default=sa.text("'15'"), nullable=True))
    op.add_column('competitors', sa.Column('user_rating', sa.REAL(), server_default=sa.text('(4.0)'), nullable=True))
    op.add_column('competitors', sa.Column('price_index', sa.REAL(), server_default=sa.text('(90.0)'), nullable=True))
    op.add_column('competitors', sa.Column('type', sa.VARCHAR(length=32), server_default=sa.text("'all'"), nullable=True))
    op.add_column('competitors', sa.Column('growth', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('competitors', sa.Column('market_share', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('competitors', sa.Column('security_mentions', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('competitors', sa.Column('innovation_velocity', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('competitors', sa.Column('feature_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.drop_constraint(None, 'competitors', type_='unique')
    op.drop_index('ix_competitors_status', table_name='competitors')
    op.drop_index('ix_competitors_category', table_name='competitors')
    op.drop_index('ix_competitors_name', table_name='competitors')
    op.create_index('ix_competitors_name', 'competitors', ['name'], unique=False)
    op.alter_column('competitors', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('competitors', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('competitors', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'monitoring'"))
    op.alter_column('competitors', 'url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('competitors', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('competitors', 'last_checked')
    op.drop_column('competitors', 'description')
    op.drop_column('competitors', 'priority')
    op.drop_column('competitors', 'category')
    op.add_column('changes', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('changes', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.add_column('changes', sa.Column('similarity', sa.REAL(), nullable=True))
    op.add_column('changes', sa.Column('content_before', sa.TEXT(), nullable=True))
    op.add_column('changes', sa.Column('content_after', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'changes', type_='foreignkey')
    op.create_foreign_key(None, 'changes', 'competitors', ['competitor_id'], ['id'])
    op.drop_index('ix_changes_detected_at', table_name='changes')
    op.drop_index('ix_changes_competitor_id', table_name='changes')
    op.create_index('idx_changes_competitor', 'changes', ['competitor_id', 'created_at'], unique=False)
    op.alter_column('changes', 'change_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('changes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('changes', 'is_read')
    op.drop_column('changes', 'detected_at')
    op.drop_column('changes', 'severity')
    op.drop_column('changes', 'new_value')
    op.drop_column('changes', 'old_value')
    op.drop_column('changes', 'field_name')
    op.add_column('analysis_reports', sa.Column('confidence', sa.FLOAT(), nullable=False))
    op.add_column('analysis_reports', sa.Column('evidence_json', sa.TEXT(), nullable=False))
    op.add_column('analysis_reports', sa.Column('recommendations_json', sa.TEXT(), nullable=False))
    op.add_column('analysis_reports', sa.Column('insight', sa.TEXT(), nullable=False))
    op.add_column('analysis_reports', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.add_column('analysis_reports', sa.Column('model_name', sa.VARCHAR(length=64), nullable=False))
    op.create_index('ix_analysis_reports_timestamp', 'analysis_reports', ['timestamp'], unique=False)
    op.alter_column('analysis_reports', 'report_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('analysis_reports', 'created_at')
    op.drop_column('analysis_reports', 'model_used')
    op.drop_column('analysis_reports', 'confidence_score')
    op.drop_column('analysis_reports', 'recommendations')
    op.drop_column('analysis_reports', 'content')
    op.drop_column('analysis_reports', 'summary')
    op.drop_column('analysis_reports', 'title')
    op.drop_index('ix_alert_history_triggered_at', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index('ix_user_reviews_competitor_id', table_name='user_reviews')
    op.drop_table('user_reviews')
    op.drop_index('ix_price_history_competitor_id', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_monitoring_snapshots_competitor_id', table_name='monitoring_snapshots')
    op.drop_table('monitoring_snapshots')
    op.drop_table('monitoring_schedule')
    op.drop_index('ix_alert_rules_competitor_id', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_table('scraper_configs')
    # ### end Alembic commands ###
